### ISSUE TITLE
Following instructions on glances github page to add glances as sensor appears not supporte

### ISSUE THREAD

**Issue by chivandikwa** [hassio-addons/addon-glances#51]
Following instructions on glances Github page to add glances as sensor appears not supported
I get the following error message:

The glances platform for the sensor integration does not support platform setup. Please remove it from your config

## Expected behavior

I expect to see a glances sensor/entity appearing in home assistance

## Actual behavior

The glances platform for the sensor integration does not support platform setup. Please remove it from your config

## Steps to reproduce

I installed the glances add on with the following configuration:

```
log_level: info
process_info: false
refresh_time: 60
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: false
  host: a0d7b954-influxdb
  port: 8086
  username: glances
  password: ''
  database: glances
  prefix: localhost
  interval: 60
```

In the configuration.yaml I added the following entry:

```
sensor:
  - platform: glances
    host: 127.0.0.1
    port: 61209
    version: 3
    resources:
      - 'disk_use_percent'
      - 'memory_use_percent'
      - 'processor_load'
      - 'process_running'
      - 'cpu_use_percent'
      - 'cpu_temp'
      - 'docker_active'
      - 'docker_cpu_use'
      - 'docker_memory_use'
```

I am running this on a raspberrypi4 with raspbian and hassio installed via docker ce.
