### ISSUE TITLE
Glances is terminated when starting up

### ISSUE THREAD

**Issue by mrosseel** [hassio-addons/addon-glances#57]
# Problem/Motivation

Glances web UI doesn't show up, logs say 'Terminated'

## Expected behavior

The logs should explain why glances was terminated

## Actual behavior

The logs say 'Terminated' and I can't figure out how to fix it.

## Steps to reproduce

Not sure how to reproduce it, I'm running a 'home assistant supervised' ubuntu installation on a laptop with ample disk/cpu. HA and system on latest stable versions.
There's an working influxdb addon running, it has a glances user and a glances db. 

This is the part of the log where glances is started with debug level 'trace'. :

```
INFO: Starting Glances...
TRACE: bashio::config: refresh_time
TRACE: bashio::jq: /data/options.json if (.refresh_time == null) then
            null
        elif (.refresh_time | type == "string") then
            .refresh_time // empty
        elif (.refresh_time | type == "boolean") then
            .refresh_time // false
        elif (.refresh_time | type == "array") then
            if (.refresh_time == []) then
                empty
            else
                .refresh_time[]
            end
        elif (.refresh_time | type == "object") then
            if (.refresh_time == {}) then
                empty
            else
                .refresh_time
            end
        else
            .refresh_time
        end
TRACE: bashio::var.false: false
TRACE: bashio::config.false: process_info
TRACE: bashio::config: process_info
TRACE: bashio::jq: /data/options.json if (.process_info == null) then
            null
        elif (.process_info | type == "string") then
            .process_info // empty
        elif (.process_info | type == "boolean") then
            .process_info // false
        elif (.process_info | type == "array") then
            if (.process_info == []) then
                empty
            else
                .process_info[]
            end
        elif (.process_info | type == "object") then
            if (.process_info == {}) then
                empty
            else
                .process_info
            end
        else
            .process_info
        end
TRACE: bashio::var.false: false
Terminated
INFO: Starting NGinx...
```

My glances config (tried ssl false/true, password with/without quotes):
```
log_level: trace
process_info: false
refresh_time: 10
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: false
  host: a0d7b954-influxdb
  port: 8086
  username: glances
  password: 'mypassword'
  database: glances
  prefix: localhost
  interval: 60
```

## Proposed changes

More info on why glances is terminated.
