### ISSUE TITLE
memory leak in glances container

### ISSUE THREAD

**Issue by kkellner** [hassio-addons/addon-glances#61]
# Problem/Motivation

When running glances add-on with influxdb configured, the glances container continous to grow in memory consumption.   280MB to 600MB in two days.

Memory consumption. Note the sharp drops were hass (hassio) restarts.
![image](https://user-images.githubusercontent.com/9540241/78516586-5343fe80-7777-11ea-9215-c3a593baf6f4.png)

From within container:
![image](https://user-images.githubusercontent.com/9540241/78516751-eda44200-7777-11ea-9ecf-9f33d5262d27.png)

## Expected behavior

Memory hits a stable state.

## Actual behavior

Memory consumption continues to climb. 

## Steps to reproduce

Using HA v0.107.7, configure glances plugin v0.7.1 as follows and wait a day or two to watch memory climb.

```yaml
log_level: info
process_info: false
refresh_time: 10
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: true
  host: a0d7b954-influxdb
  port: 8086
  username: glances
  password: mypasword
  database: glances
  prefix: localhost
  interval: 60
```

## Proposed changes

none
